[project]
name = "onedl-mmtracking"
version = "1.1.0"
description = "OneDL Unified Video Perception Platform"
readme = "README.md"
authors = [
    {name = "OneDL MMTracking Contributors"},
    {name = "VBTI Open Source Team", email = "oss-team@vbti.nl"}
]
license = "LicenseRef-Apache-2.0"
requires-python = ">=3.10"
keywords = ["computer vision", "object tracking", "video object detection"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "attributee",
    "lap",
    "matplotlib",
    "motmetrics",
    "pycocotools",
    "scikit-learn",
    "scipy",
    "seaborn",
    "tabulate",
    "tqdm",
    "trackeval",
]

[project.urls]
Homepage = "https://github.com/VBTI-development/onedl-mmtracking"
Repository = "https://github.com/VBTI-development/onedl-mmtracking"
Documentation = "https://onedl-mmtracking.readthedocs.io/en/latest/"

[dependency-groups]
build = [
    "cython",
    "numpy"
]
docs = [
    "myst-parser",
    "pytorch_sphinx_theme @ git+https://github.com/VBTI-development/onedl_sphinx_theme.git",
    "sphinx",
    "sphinx-copybutton",
    "sphinx_markdown_tables",
]
readthedocs = [
    "onedl-mmcv",
    "onedl-mmengine",
    "onedl-mmdetection",
    "torch",
    "torchvision"
]
tests = [
    "asynctest",
    "codecov",
    "parameterized",
    "pytest",
    "xdoctest>=0.10.0",
    "vot-toolkit @ git+https://github.com/votchallenge/toolkit.git",
]

[project.optional-dependencies]
torch = [ "torch", "torchvision" ]
mminstall = [
    "onedl-mmpretrain",
    "onedl-mmcv",
    "onedl-mmdetection[optional]",
    "onedl-mmengine",
]

[tool.setuptools.packages.find]
include = [ "mmtrack", "mmtrack.*" ]
exclude = ["configs", "tools", "demo"]
namespaces = false

[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[tool.isort]
line_length = 79
multi_line_output = 0
extra_standard_library = ["setuptools"]
known_first_party = ["mmtrack"]
known_third_party = [
    "PIL",
    "addict",
    "cv2",
    "lap",
    "matplotlib",
    "mmcls",
    "mmcv",
    "mmdet",
    "motmetrics",
    "numpy",
    "packaging",
    "pandas",
    "pycocotools",
    "pytest",
    "pytorch_sphinx_theme",
    "requests",
    "scipy",
    "script_utils",
    "seaborn",
    "tao",
    "terminaltables",
    "torch",
    "tqdm"
]
no_lines_before = ["STDLIB", "LOCALFOLDER"]
default_section = "THIRDPARTY"  # codespell:ignore

[tool.yapf]
based_on_style = "pep8"
blank_line_before_nested_class_or_def = true
split_before_expression_after_opening_paren = true

[tool.codespell]
skip = "*.ipynb,configs/v3det/category_name_13204_v3det_2023_v1.txt,**/labels_names.json,tools/dataset_converters/zhiyuan_objv2_train_names_fix.csv"
quiet-level = 3
ignore-words-list = "patten,nd,ty,mot,hist,formating,winn,gool,datas,wan,confids,TOOD,tood,ba,warmup,nam,DOTA,dota,conveyer,PRES,insId,burnin"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--xdoctest --xdoctest-style=auto"
norecursedirs = ".git ignore build __pycache__ data docker docs .eggs"
filterwarnings = [
    "default",
    "ignore:.*No cfgstr given in Cacher constructor or call.*:Warning",
    "ignore:.*Define the __nice__ method for.*:Warning"
]
